### ISSUE TITLE
If changelog.xml is empty, auto-add migration to changelog.xml fails silently 

### ISSUE THREAD

**Issue by dannov91** [wawandco/liquo#4]
I think this is more of a feature request. Here it goes:

I created a blank `changelog.xml` file in the `{name_of_app}/migrations` folder (because I don't exactly remember what it should include), and when I run the `ox generate migration xxx` command, it creates the migration file but adds nothing to the `changelog.xml` file.

I expected a warning or an error telling that either the `changelog.xml` file was not present or that it did not have the expected format. 

Also I think we should tell in the README that it adds automatically the migration path to the `changelog.xml`, I didn't know it had such a cool feature!

**Comment by paganotoni** [comment]
Oh! This is a good one. Yeah, definitely a case we have not covered. thanks @dannov91

**Comment by paganotoni** [comment]
Solved with #7

**Comment by paganotoni** [comment]
Thanks @dannov91 !
