### ISSUE TITLE
Feature Request: ox generate/check liquo changelog.xml

### ISSUE THREAD

**Issue by dannov91** [wawandco/liquo#5]
From the [previous issue](https://github.com/wawandco/liquo/issues/4), I mentioned I did not remember exactly what a `changelog.xml` should contain in order for liquo to work correctly.

I think that a generator/check for this kind of file should be really helpful! :)

**Comment by paganotoni** [comment]
Agreed. Thanks @dannov91 this is great.

**Comment by paganotoni** [comment]
Solved with #9. Thanks @dannov91
